FROM kernsuite/base:9

# Get kern packages
RUN docker-apt-install \
    wsclean \
    casacore-dev

# Get other packages
RUN docker-apt-install \
    git \
    curl \
    ca-certificates \
    python3 \
    python-is-python3

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"
RUN uv pip install --system git+https://gitlab.com/Sunmish/potato.git