name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker images to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        name: [calibrate, askapsoft, aoflagger, wsclean, aegean, potato, casa]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CALIBRATE_TOKEN }}

      - name: Determine tag suffix
        id: tag_suffix
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "TAG_SUFFIX=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            SHORT_HASH=$(git rev-parse --short HEAD)
            LATEST_RELEASE=$(git describe --tags --abbrev=0 || echo "latest")
            echo "TAG_SUFFIX=${LATEST_RELEASE}-${SHORT_HASH}" >> $GITHUB_ENV
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/flint-containers
          tags: |
            type=raw,value=${{ matrix.name }}-${{ env.TAG_SUFFIX }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-${{ matrix.name }}  # Builds the correct Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/flint-containers:${{ matrix.name }}-${{ env.TAG_SUFFIX }}  # Explicitly set tag
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Debug build output
        run: |
          docker images ghcr.io/${{ github.repository_owner }}/flint-containers

      - name: Debug attestation input
        run: |
          echo "Subject name: ghcr.io/${{ github.repository_owner }}/flint-containers:${{ matrix.name }}-${{ env.TAG_SUFFIX }}"
          echo "Subject digest: ${{ steps.push.outputs.digest }}"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          push-to-registry: true
