name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker images to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        name: [calibrate, askapsoft, aoflagger, wsclean, aegean, potato, casa]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CALIBRATE_TOKEN }} 

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/flint-containers
          tags: |
            type=raw,value=${{ matrix.name }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-${{ matrix.name }}  # Builds the correct Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/flint-containers:${{ matrix.name }}  # Explicitly set tag
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Debug build output
        run: |
          docker images ghcr.io/${{ github.repository_owner }}/flint-containers

      - name: Debug attestation input
        run: |
          echo "Subject name: ghcr.io/${{ github.repository_owner }}/flint-containers:${{ matrix.name }}"
          echo "Subject digest: ${{ steps.push.outputs.digest }}"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/flint-containers:${{ matrix.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

