name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker images to GHCR
    runs-on: ubuntu-latest
    continue-on-error: true  # Ensures all matrix jobs run even if one fails
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        name: [calibrate, askapsoft, aoflagger, wsclean, aegean, potato, casa]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/flint-containers:${{ matrix.name }}
        run: |
          docker build -f Dockerfile-${{ matrix.name }} -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Generate artifact attestation
        run: |
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME | cut -d "@" -f 2)
          gh workflow run actions/attest-build-provenance@v2 --with "subject-name=$IMAGE_NAME,subject-digest=$digest,push-to-registry=true"
